repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-specific-version
        name: Pyrefly
        pass_filenames: false
        additional_dependencies: ["pyrefly==0.1.0"]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: uv run pytest tests/ --no-cov -q
        language: system
        pass_filenames: false
        always_run: true
