{#
  Auto-generated by dbt-multi-adapter-utils
  Generated: 2025-10-15 08:10:36
  DO NOT EDIT MANUALLY

  Regenerate with: dbt-multi-adapter-utils generate
#}

{% macro portable_count(expression) -%}
    {{ return(adapter.dispatch('count', 'portable')(expression)) }}
{%- endmacro %}

{% macro postgres__count(expression) -%}
    COUNT({{ expression }})
{%- endmacro %}

{% macro snowflake__count(expression) -%}
    COUNT({{ expression }})
{%- endmacro %}

{% macro bigquery__count(expression) -%}
    COUNT({{ expression }})
{%- endmacro %}

{% macro portable_current_date(expression) -%}
    {{ return(adapter.dispatch('current_date', 'portable')(expression)) }}
{%- endmacro %}

{% macro postgres__current_date(expression) -%}
    CURRENT_DATE AT TIME ZONE {{ expression }}
{%- endmacro %}

{% macro snowflake__current_date(expression) -%}
    CAST(CONVERT_TIMEZONE({{ expression }}, CURRENT_TIMESTAMP()) AS DATE)
{%- endmacro %}

{% macro bigquery__current_date(expression) -%}
    CURRENT_DATE({{ expression }})
{%- endmacro %}

{% macro portable_date_trunc(expression) -%}
    {{ return(adapter.dispatch('date_trunc', 'portable')(expression)) }}
{%- endmacro %}

{% macro postgres__date_trunc(expression) -%}
    DATE_TRUNC({{ expression }})
{%- endmacro %}

{% macro snowflake__date_trunc(expression) -%}
    DATE_TRUNC({{ expression }})
{%- endmacro %}

{% macro bigquery__date_trunc(expression) -%}
    DATE_TRUNC({{ expression }})
{%- endmacro %}

